services:
  postgres:
    image: postgres:16
    container_name: erp-postgres
    environment:
      POSTGRES_DB: erp_integration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: erp-kafka
    ports:
      - "29092:29092"   # host access (optional)
      - "9092:9092"     # internal network (kafka-ui + middleware)
    environment:
      # KRaft single-node
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Dev defaults
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

    volumes:
      - kafkadata:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: erp-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"

  middleware:
    container_name: erp-middleware
    build:
      context: .
      dockerfile: Middleware.Api/Dockerfile
    depends_on:
      - kafka
      - postgres
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=erp_integration;Username=postgres;Password=postgres"
      Security__WebhookSecret: "super-secret"
      Security__AllowedClockSkewSeconds: "300"
      Kafka__BootstrapServers: "kafka:9092"
      Kafka__Topic: "erp.personnel.lifecycle"

volumes:
  pgdata:
  kafkadata: